//
// Generated file, do not edit! Created by nedtool 5.6 from userMsg.msg.
//

#ifndef __USERMSG_M_H
#define __USERMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


class UserMsg_Base : public ::omnetpp::cPacket
{
  protected:
    int someField;
    ::omnetpp::opp_string msg;

  private:
    void copy(const UserMsg_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UserMsg_Base&);
    // make constructors protected to avoid instantiation
    UserMsg_Base(const UserMsg_Base& other);
    // make assignment operator protected to force the user override it
    UserMsg_Base& operator=(const UserMsg_Base& other);

  public:
    virtual ~UserMsg_Base();
    UserMsg_Base(const char *name=nullptr, short kind=0);
    virtual UserMsg_Base *dup() const override {return new UserMsg_Base(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSomeField() const;
    virtual void setSomeField(int someField);
    virtual const char * getMsg() const;
    virtual void setMsg(const char * msg);
};


#endif // ifndef __USERMSG_M_H

